let constants = require('./ecmascript2016/01.constants/constants');
let variables = require('./ecmascript2016/02.scoping/variables');
let functions = require('./ecmascript2016/02.scoping/functions');
let arrows = require('./ecmascript2016/03.arrow-functions/arrows');
let defaultParameter = require('./ecmascript2016/04.parameter-handling/default-parameter');
let restParameter = require('./ecmascript2016/04.parameter-handling/rest-parameter');
let spread = require('./ecmascript2016/04.parameter-handling/spread');
let stringLiteral = require('./ecmascript2016/05.literal/string-literal');
let numberLiteral = require('./ecmascript2016/05.literal/number-literal');
let propertyAssign = require('./ecmascript2016/06.object-properties/property-assign');
let computedPropoertyName = require('./ecmascript2016/06.object-properties/computed-property-name');
let methodPropoerty = require('./ecmascript2016/06.object-properties/method-property');
let arrayMatching = require('./ecmascript2016/07.destructuring-assignment/array-matching');
let objectMatching = require('./ecmascript2016/07.destructuring-assignment/object-matching');
let parameterMatching = require('./ecmascript2016/07.destructuring-assignment/parameter-matching');
//let modules = require('./ecmascript2016/08.modules/client');
let classes = require('./ecmascript2016/09.classes/classes');
let symbols = require('./ecmascript2016/10.symbols/symbols');
let iterators = require('./ecmascript2016/11.iterators/iterators');
let functionGenerator = require('./ecmascript2016/12.generators/function-generator');
let set = require('./ecmascript2016/13.set-map/set');
let map = require('./ecmascript2016/13.set-map/map');
let objectExtending = require('./ecmascript2016/14.object-extending/object-extending');
let arrayFinding = require('./ecmascript2016/15.array-finding/array-finding');
let stringRepeat = require('./ecmascript2016/16.string-methods/string-repeat');
let stringSearch = require('./ecmascript2016/16.string-methods/string-search');

// constants();
// variables();
// functions();
// arrows();
// defaultParameter();
// restParameter();
// spread();
// stringLiteral();
// numberLiteral();
// propertyAssign();
// computedPropoertyName();
// methodPropoerty();
// arrayMatching();
// objectMatching();
// parameterMatching();
// modules();
// classes();
// symbols();
// iterators();
// functionGenerator();
// set();
// map();
// objectExtending();
// arrayFinding();
// stringRepeat();
// stringSearch();